<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <EnableExpectoTestingPlatformIntegration>true</EnableExpectoTestingPlatformIntegration>
    <OutputType>Exe</OutputType>
    <GenerateProgramFile>false</GenerateProgramFile>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>

    <!-- NOTE: For output to console. -->
    <TestingPlatformCaptureOutput>false</TestingPlatformCaptureOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" />
    <PackageReference Include="Expecto.FsCheck" />
    <PackageReference Include="FsCheck" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SampleModule/SampleModule.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Core.fs" />
  </ItemGroup>

</Project>