<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.0.1</Version>
    <Description>A sample PowerShell module.</Description>
    <Copyright>Copyright © 2026 Takatoshi Kuriyama. All rights reserved.</Copyright>

    <TargetFramework>net8.0</TargetFramework>

    <!-- Deploy the produced assembly -->
    <PublishDir>../../publish/SampleModule</PublishDir>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <!-- Disable PDB generation for the Release build -->
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Core.fs" />
    <Compile Include="Predictor.fs" />
    <Compile Include="FeedbackProvider.fs" />
    <Compile Include="Cmdlet.fs" />
    <Compile Include="Init.fs" />

    <Content Include="SampleModule.psd1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
